"""
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

# Approach
1. need to find a way to randomly shuffle a word.
2. need to find a way to randomly generate a letter.
3. randomly generate a number within contraints.
"""

def findTheDifference(self, s: str, t: str) -> str:
    